config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'profile', to: 'users#profile'
  get 'details', to: 'pages#details'
  get 'dashboard', to: 'employers#dashboard'

  # mount ActionCable.server => '/cable'
  resources :charities, only: %i[create show] do
    resources :events, only: %i[new create]
  end
  resources :events, only: %i[index show destroy edit update] do
    resources :bookings, only: %i[new create]
  end
  resources :employers, only: %i[create dashboard]
  resources :volunteers, only: %i[create]
  resources :chatrooms, only: %i[index show] do
    resources :messages, only: %i[create]
  end
  resources :users, only: %i[] do
    patch '/accept/:id', to: 'invitations#accept', as: 'accept'
    patch '/decline/:id', to: 'invitations#decline', as: 'decline'
    resources :chatrooms, only: %i[create]
  end
  resources :bookings, only: %i[index destroy]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :charity

  has_many :bookings

  validates :address, :event_name, :date, :start_time, :duration, :description, :number_positions, presence: true
  validates :duration, inclusion: { in: (1..8) }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(strong_params)
    @charity = Charity.find(params[:charity_id])
    @event.charity = @charity
    if @event.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def index
    @events = Event.all
    @markers = @events.geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        info_window: render_to_string(partial: "info_window", locals: { event: event }),
        image_url: helpers.asset_url("MapMarker.png")
      }
    end

    @sports_charities = Charity.where(category: "Sports")
    @sports_category_events = []
    @sports_charities.each do |charity|
      charity.events.each do |event|
      if event.date >= DateTime.now
        @sports_category_events << event
      end
      end
    end

    @human_welfare_charities = Charity.where(category: "Human Welfare")
    @human_welfare_category_events = []
    @human_welfare_charities.each do |charity|
      charity.events.each do |event|
      if event.date >= DateTime.now
        @human_welfare_category_events << event
      end
      end
    end

    @animal_welfare_charities = Charity.where(category: "Animal Welfare")
    @animal_welfare_category_events = []
    @animal_welfare_charities.each do |charity|
      charity.events.each do |event|
        if event.date >= DateTime.now
          @animal_welfare_category_events << event
        end
      end
    end

    @environment_charities = Charity.where(category: "Environment")
    @environment_category_events = []
    @environment_charities.each do |charity|
      charity.events.each do |event|
        if event.date >= DateTime.now
          @environment_category_events << event
        end
      end
    end

    @charity_shops_charities = Charity.where(category: "Charity Shops")
    @charity_shops_category_events = []
    @charity_shops_charities.each do |charity|
      charity.events.each do |event|
        if event.date >= DateTime.now
          @charity_shops_category_events << event
        end
      end
    end
  end

  def show
    @event = Event.find(params[:id])
    @user = @event.charity.user.id
  end

  def event_params
    params.require(:event).permit(:address, :date, :start_time, :duration, :event_name, :description, :number_positions)
  end
end

app/views/events/_card.html.erb
<% human_welfare =  ['https://images.unsplash.com/photo-1582803824594-65b5b4632cad?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1471&q=80',
                  'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
                  'https://images.unsplash.com/photo-1608342381036-15657da6bf58?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
                  'https://images.unsplash.com/photo-1601572545227-de6842f88454?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
                  'https://images.unsplash.com/photo-1511632765486-a01980e01a18?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80']
animal_welfare = ['https://images.unsplash.com/photo-1548767797-d8c844163c4c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1471&q=80',
                  'https://images.unsplash.com/photo-1444212477490-ca407925329e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1528&q=80',
                  'https://images.unsplash.com/photo-1454179083322-198bb4daae41?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
                  'https://images.unsplash.com/photo-1450778869180-41d0601e046e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1586&q=80',
                  'https://images.unsplash.com/photo-1601758177266-bc599de87707?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80']
environment =  ['https://images.unsplash.com/photo-1466611653911-95081537e5b7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
                'https://images.unsplash.com/photo-1416169607655-0c2b3ce2e1cc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80',
                'https://images.unsplash.com/photo-1498925008800-019c7d59d903?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80',
                'https://images.unsplash.com/photo-1445346753792-6c667d917349?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
                'https://images.unsplash.com/photo-1431057259500-78dd318a0a75?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80']
sports = ['https://images.unsplash.com/photo-1552674605-db6ffd4facb5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
          'https://images.unsplash.com/photo-1459865264687-595d652de67e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
          'https://images.unsplash.com/photo-1547347298-4074fc3086f0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
          'https://images.unsplash.com/photo-1484482340112-e1e2682b4856?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1476&q=80',
          'https://images.unsplash.com/photo-1530549387789-4c1017266635?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80']
charity_shops =  ['https://images.unsplash.com/photo-1470309864661-68328b2cd0a5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
                  'https://images.unsplash.com/photo-1615897570286-da936a5dfb81?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1521&q=80',
                  'https://images.unsplash.com/photo-1521335629791-ce4aec67dd15?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
                  'https://images.unsplash.com/photo-1615897570582-285ffe259530?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
                  'https://images.unsplash.com/photo-1556740772-1a741367b93e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80']  %>


<%= link_to event_path(event), class:"card-link" do %>
  <% number = $counter %>
  <% image_url =
    if event.charity.category == "Human Welfare"
      human_welfare[number]
    elsif event.charity.category == "Animal Welfare"
      animal_welfare[number]
    elsif event.charity.category == "Environment"
      environment[number]
    elsif event.charity.category == "Sports"
      sports[number]
    elsif event.charity.category == "Charity Shops"
      charity_shops[number]
    end %>

  <div class="card-home">
    <div>
      <%= image_tag image_url, class:"card-image" %>
    </div>
    <div class="card-text">
      <h4 class="card-title"><%= event.event_name %></h4>
      <h5><%= event.charity.charity_name %></h5>
      <p class="address"><%= event.address.split(",").first %></p>
      <p><i class="fas fa-calendar-week icon-pink"></i> <%= event.date.strftime("%e %b %y") %></p>
      <div class="timings">
        <p><i class="fas fa-clock icon-pink"></i> <%= event.start_time.strftime("%H:%M") %></p>
        <p><i class="fas fa-hourglass-start icon-pink"></i> <%= event.duration %>
        <% if event.duration == 1 %>
          hour</p>
        <% else %>
          hours</p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/events/_info_window.html.erb
<h5><%= event.event_name %></h5>
<p><%= event.charity.charity_name %></p>
<p><%= event.address %></p>
<%# <a class="button" id="infocard" href=" ">Go to event</a> %>
<%= link_to "Go to event", event_path(event), class: "button", id: "infocard" %>

app/views/events/index.html.erb
<div class="app">
  <div class="mapbox-container">
    <div class="map" id="map-size" style="width: 96%; height: 400px; color: white; border: none;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

  <h3 class="carousel-card">Human Welfare</h3>
  <ul class="hs full no-scrollbar">
    <% $counter = 0 %>
    <% @human_welfare_category_events.each do |event| %>
      <li class="item"> <%= render partial: 'card', locals: {event: event} %> </li>
      <% $counter >= 4 ? $counter = 0 : $counter += 1 %>
    <% end %>
  </ul>

  <h3 class="carousel-card">Animal Welfare</h3>
  <ul class="hs full no-scrollbar">
    <% $counter = 0 %>
    <% @animal_welfare_category_events.each do |event| %>
      <li class="item"> <%= render partial: 'card', locals: {event: event} %> </li>
      <% $counter >= 4 ? $counter = 0 : $counter += 1 %>
    <% end %>
  </ul>

  <h3 class="carousel-card">Environment</h3>
  <ul class="hs full no-scrollbar">
    <% $counter = 0 %>
    <% @environment_category_events.each do |event| %>
      <li class="item"> <%= render partial: 'card', locals: {event: event} %> </li>
      <% $counter >= 4 ? $counter = 0 : $counter += 1 %>
    <% end %>
  </ul>

  <h3 class="carousel-card">Sports</h3>
  <ul class="hs full no-scrollbar">
    <% $counter = 0 %>
    <% @sports_category_events.each do |event| %>
      <li class="item"> <%= render partial: 'card', locals: {event: event} %> </li>
      <% $counter >= 4 ? $counter = 0 : $counter += 1 %>
    <% end %>
  </ul>

  <h3 class="carousel-card">Charity Shops</h3>
  <ul class="hs full no-scrollbar">
    <% $counter = 0 %>
    <% @charity_shops_category_events.each do |event| %>
      <li class="item"> <%= render partial: 'card', locals: {event: event} %> </li>
      <% $counter >= 4 ? $counter = 0 : $counter += 1 %>
    <% end %>
  </ul>
</div>

app/views/events/new.html.erb
<div class="booking-card container">
  <h1>Add the event for your charity</h1>
   <h1 class="booking-form-charity-event"></h1>

  <div>
    <%= simple_form_for [@event ] do |f| %>
      <%= f.input :date, label: 'Date', as: :date %>
      <%= f.input :start_time, label: 'Time', as: :time %>
      <%= f.input :location, label: 'Location', as: :string %>
      <%= f.input :duration, label: 'Duration (Hours):', collection: 1..18 %>
      <%= f.input :number_position, label: 'Number of positions:', as: :integer %>
      <%= f.submit 'Confirm Event', class:"btn btn-success" %>
    <% end %>
  </div>

  <%= #link_to bookings_path(@booking) do %>?
  <% end %>
</div>

app/views/events/show.html.erb
<% content_for :meta_title, "#{DEFAULT_META["meta_product_name"]} - #{@event.event_name}" %>
<% content_for :meta_description, @event.description %>
<%# content_for :meta_image, cl_image_path(@offer.photo.path) %>

<% img_url = "https://images.unsplash.com/photo-1578357078586-491adf1aa5ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dm9sdW50ZWVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60" %>


<div class="banner-img">
  <img src=<%= img_url %> alt="holding hands">
</div>

<div class="container">
  <div class="event-details">

    <div class="title-and-back">
      <h3><%= @event.event_name %></h3>
      <%= link_to events_path do %>
        <i class="fas fa-arrow-circle-left icon-pink-clickable"></i>
      <% end %>
    </div>

    <h5><%= @event.charity.charity_name %>
      <%= link_to charity_path(@event.charity) do %>
        <i class="fas fa-info-circle "></i>
      <% end %>
    </h5>
    <p><%= @event.address %></p>

    <div class="event-timings">
      <div class="event-timings-detail">
        <i class="fas fa-calendar-week icon-pink"></i>
        <h4><%= @event.date.strftime("%e %b %y") %></h4>
      </div>
      <div class="event-timings-detail">
        <i class="fas fa-clock icon-pink"></i>
        <h4><%= @event.start_time.strftime("%H:%M") %></h4>
      </div>
      <div class="event-timings-detail">
        <i class="fas fa-hourglass-start icon-pink"></i>
        <h4>
          <% if @event.duration ==1 %>
            <%= "#{@event.duration} hour" %>
          <% else %>
            <%= "#{@event.duration} hours" %>
          <% end %>
        </h4>
      </div>
    </div>
</div>

  <div class="responsibilites" data-controller="show-more">
    <div class="list full-list d-none" data-show-more-target="fulllist">
      <h5>Overview of responsibilites</h5>
      <ul>
        <% responsibilities = @event.description.split(".") %>
        <% responsibilities.each do |responsibility| %>
          <li><%= responsibility %>.</li>
        <% end %>
        <div class="unhide-hide-button">
          <button class="unhide-hide" data-action="click->show-more#hide">show less</button>
        </div>
      </ul>
    </div>

    <div class="list short-list" data-show-more-target="shortlist">
      <h5>Overview of responsibilites</h5>
      <ul>
        <li><%= @event.description[0,150] %>...</li>
        <div class="unhide-hide-button">
          <button class="unhide-hide" data-action="click->show-more#unhide">show more</button>
        </div>
      </ul>
    </div>
  </div>

    <div class="button-container">
        <%= link_to user_chatrooms_path(@user), method: :post, class:"chat-button" do %>
          <i class="fas fa-comment-medical"></i>
        <% end %>
    </div>

  <div class="button-background" id="book-now">
    <div style="height:40px" class="button">
      <%= link_to "Book now", new_event_booking_path(@event) %>
    </div>
  </div>

</div>